Repository High-Table-Consortium/fullstack-capstone-dockerized, pull requests merged in 2024-09, with the labels that each got.

#6 Add Tourist Attraction Model
  server/server/models/adminModel.js
  server/server/models/tourist_attractionModel.js
Labels: feature/enhancement

#9 feat(models): add Review schema linking users and attractions
  server/server/models/reviewModel.js
Labels: feature/enhancement

#16 Implement authentication for admin users
  server/.env
  server/package-lock.json
  server/package.json
  server/server/controllers/adminController.js
  server/server/middleware/authMiddleware.js
  server/server/models/adminModel.js
  server/yarn.lock
Labels: feature/enhancement

#31 Add Admin Routes for Registration, Login, and Protected Access
  server/server/controllers/adminController.js
  server/server/index.js
  server/server/routes/adminRoutes.js
Labels: feature/enhancement

#37 Add user routes for registration, login, profile retrieval, and updates
  server/server/routes/userRoutes.js
Labels: feature/enhancement

#38 Review page
  client/package-lock.json
  client/package.json
  client/src/app/components/Forms.jsx
  client/src/app/components/Searchbar.jsx
  client/src/app/components/Test.jsx
  client/src/app/layout.js
  client/src/app/pages/reviewlandingpage.jsx
  client/src/app/pages/reviewpage.jsx
  client/src/app/pages/signin.jsx
Labels: feature/enhancement

#43 Explore page
  client/src/app/explore/page.jsx
  client/src/app/review/page.jsx
  client/src/app/reviewsearch/page.jsx
Labels: feature/enhancement

#45 add attraction controllers and update attraction model
  server/server/index.js
  server/server/models/tourist_attractionModel.js
  server/server/routes/attractionRoutes.js
Labels: feature/enhancement

#40 20-footer
  client/components.json
  client/package-lock.json
  client/package.json
  client/src/app/components/Footer.jsx
  client/src/app/globals.css
  client/src/app/layout.js
  client/src/lib/utils.js
  client/tailwind.config.js
Labels: documentation

#46 Added the NavBar,ui folder and editted the footer
  client/components.json
  client/package-lock.json
  client/package.json
  client/src/app/components/Reviewcard.jsx
  client/src/app/explore/page.jsx
  client/src/app/layout.js
  client/src/app/page.js
  client/src/components/Buttons.jsx
  client/src/components/Footer.jsx
  client/src/components/Forms.jsx
  client/src/components/Map.jsx
  client/src/components/Navbar.jsx
  client/src/components/Pagination.jsx
  client/src/components/PictureCard.jsx
  client/src/components/Ratings.jsx
  client/src/components/Reviewcard.jsx
  client/src/components/Searchbar.jsx
  client/src/components/Test.jsx
  client/src/components/ui/avatar.jsx
  client/src/components/ui/button.jsx
  client/src/components/ui/dropdown-menu.jsx
Labels: feature/enhancement

#49 Add attraction controllers (getAllAttractionSites, getAttractionSiteB…
  server/server/controllers/attractionSiteController.js
Labels: feature/enhancement

#48 Refactor user routes for improved functionality
  server/server/routes/userRoutes.js
Labels: feature/enhancement

#52 Add user controller functionality: Implement registration, login, pro…
  server/server/controllers/userController.js
  server/server/routes/reviewRoutes.js
  server/server/routes/userRoutes.js
Labels: feature/enhancement

#56 Refactor: Add Descriptive Comments to recommendations.js
  server/package-lock.json
  server/package.json
  server/server/controllers/recommendations.js
  server/server/index.js
  server/server/routes/recommendationsroute.js
  server/yarn.lock
Labels: documentation

#58 added signin and signup, edited nav bar
  client/package-lock.json
  client/package.json
  client/src/app/auth/signin/page.jsx
  client/src/app/auth/signup/page.jsx
  client/src/components/Navbar.jsx
  client/src/components/ui/input.jsx
  client/src/components/ui/label.jsx
  client/src/hooks/use-toast.js
Labels: bug

#25 Created User Schema
  server/server/models/usersModel.js
Labels: feature/enhancement
