Repository High-Table-Consortium/fullstack-capstone-dockerized, pull requests merged in 2024-10, with the labels that each got.

#73 Add handleValidationErrors Middleware
  server/server/middleware/handleValidation.js
Labels: feature/enhancement

#75 Implement Comment Functionality for Attraction Sites
  server/server/controllers/commentController.js
  server/server/index.js
  server/server/routes/commentRoutes.js
Labels: feature/enhancement

#77 Add Google OAuth Authentication Using Passport.js
  server/.env
  server/index.js
  server/package-lock.json
  server/package.json
  server/server/middleware/passportConfig.js
  server/server/models/usersModel.js
  server/server/routes/authenticationRoutes.js
  server/yarn.lock
Labels: documentation, feature/enhancement

#78 fix import for recommendation, comments, attractions
  server/index.js
Labels: bug

#80 Add Review services to Review Controller and Fix Import Issues
  server/index.js
  server/package-lock.json
  server/package.json
  server/server/controllers/adminController.js
  server/server/controllers/attractionSiteController.js
  server/server/controllers/commentController.js
  server/server/controllers/recommendations.js
  server/server/controllers/reviewController.js
  server/server/controllers/userController.js
  server/server/services/reviewService.js
Labels: bug, documentation, feature/enhancement

#85 Added a new layout for homepage and fix imports
  client/components.json
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/src/app/API/api.js
  client/src/app/API/api.ts
  client/src/app/auth/signin/page.jsx
  client/src/app/auth/signup/page.jsx
  client/src/app/explore/page.jsx
  client/src/app/homepage/page.jsx
  client/src/app/page.jsx
  client/src/components/Navbar.jsx
  client/src/components/ui/avatar.jsx
  client/src/components/ui/button.jsx
  client/src/components/ui/card.jsx
  client/src/components/ui/dropdown-menu.jsx
  client/src/components/ui/input.jsx
  client/src/components/ui/label.jsx
  client/tsconfig.json
Labels: bug, feature/enhancement

#91 Add allowed image domains, add homepage in main page.js instead of making a route
  client/next.config.mjs
  client/src/app/API/api.ts
  client/src/app/auth/signup/page.jsx
  client/src/app/homepage/page.jsx
  client/src/app/page.jsx
Labels: feature/enhancement, File Structure

#93 Fix and Implement User Authentication (Login and Register)
  client/src/app/API/api.ts
  server/server/controllers/userController.js
  server/server/index.js
  server/server/models/usersModel.js
Labels: bug

#96 Implement FastAPI Itinerary Generation Application
  AI/.gitignore
  AI/app.py
  AI/readme.md
  AI/requirements.txt
  client/src/app/API/api.ts
  client/src/app/page.jsx
  client/src/components/DetailedPageSkeleton.jsx
  client/src/components/ReviewSection.jsx
  client/src/components/ui/dialog.jsx
  client/src/components/ui/skeleton.jsx
  client/src/components/ui/textarea.jsx
Labels: documentation, feature/enhancement

#98 Destination page draft
  client/src/app/destinationlist/page.jsx
Labels: feature/enhancement

#99 (Debugging): - Server side authentication for user login and register
  server/package-lock.json
  server/package.json
  server/server/controllers/userController.js
  server/server/index.js
  server/server/middleware/authMiddleware.js
  server/server/models/usersModel.js
  server/server/tests/auththenticationController.test.js
  server/server/tests/userController.test.js
Labels: bug, feature/enhancement, Testing

#101 added the about us pagehere users can save and organize their preferred attractions, locations, or activities.
  client/next.config.mjs
  client/package-lock.json
  client/package.json
  client/src/app/about/page.jsx
Labels: feature/enhancement

#103 Implement Comment Functionality and API Requests
  client/package.json
  client/src/app/API/api.ts
  client/src/app/destination/[id]/loading.js
  client/src/app/destination/[id]/page.jsx
  client/src/components/Navbar.jsx
Labels: feature/enhancement

#107 Enhance and Fix User Authentication
  client/src/app/auth/signin/page.jsx
  client/src/app/auth/signup/page.jsx
  client/src/app/layout.js
  client/src/context/authContent.jsx
  server/.env.example
  server/package.json
  server/server/controllers/userController.js
  server/server/mailtrap/emailTemplates.js
  server/server/mailtrap/emails.js
  server/server/mailtrap/mailtrap.config.js
  server/server/middleware/authMiddleware.js
  server/server/models/usersModel.js
  server/server/routes/authenticationRoutes.js
  server/server/utils/generateTokenAndSetCookie.js
Labels: bug, feature/enhancement

#112 added a favourites page where users can view and manage their favouri…
  client/next.config.mjs
  client/package-lock.json
  client/src/app/favourites/page.jsx
  client/src/components/Navbar.jsx
  client/src/components/ui/select.jsx
Labels: feature/enhancement

#113 Fixing user authentication on the frontend and server,
  client/middleware.ts
  client/package.json
  client/src/app/API/api.ts
  client/src/app/auth/forgot-password/page.jsx
  client/src/app/auth/reset-password/page.jsx
  client/src/app/auth/signin/page.jsx
  client/src/app/auth/signup/page.jsx
  client/src/app/auth/verify-email/page.jsx
  client/src/app/layout.js
  client/src/app/page.jsx
  client/src/components/PasswordStrengthMeter.jsx
  client/src/components/ReviewSection.jsx
  client/src/context/authContent.jsx
  server/server/controllers/reviewController.js
  server/server/controllers/userController.js
  server/server/mailtrap/emails.js
  server/server/middleware/authMiddleware.js
  server/server/middleware/passportConfig.js
  server/server/routes/authenticationRoutes.js
  server/server/routes/reviewRoutes.js
  server/server/services/reviewService.js
Labels: bug, feature/enhancement

#120 Favourates page
  client/next.config.mjs
  client/package-lock.json
  client/src/app/favourites/page.jsx
  package-lock.json
  server/docker-compose.yml
  server/package-lock.json
  server/server/controllers/favourites.js
  server/server/db/connection.js
  server/server/index.js
  server/server/models/favourites.js
  server/server/routes/favourites.js
  server/yarn.lock
Labels: feature/enhancement

#127 authentication and profile (frontend and backend)
  client/middleware.ts
  client/package.json
  client/src/app/API/api.ts
  client/src/app/account/page.jsx
  client/src/app/actions/auth.ts
  client/src/app/layout.js
  client/src/components/Forms.jsx
  client/src/components/ReviewSection.jsx
  client/src/components/ui/scroll-area.jsx
  client/src/components/ui/sheet.jsx
  client/src/context/authContent.jsx
  server/server/controllers/adminController.js
  server/server/controllers/reviewController.js
  server/server/middleware/authMiddleware.js
  server/server/routes/adminRoutes.js
  server/server/routes/attractionRoutes.js
  server/server/routes/reviewRoutes.js
  server/server/routes/userRoutes.js
  server/server/services/reviewService.js
  server/server/utils/generateTokenAndSetCookie.js
Labels: bug, feature/enhancement

#128 Add new endpoints for AI and added a chatbot interface
  AI/app.py
  AI/readme.md
  client/src/components/Chatbot.jsx
Labels: feature/enhancement

#129 made changes to get attraction algorithm
  server/server/controllers/attractionSiteController.js
Labels: feature/enhancement

#131 Replaced tokens with user sessions, fixed user and admin authentication
  client/src/app/API/api.ts
  client/src/app/actions/auth.ts
  client/src/app/auth/signin/page.jsx
  client/src/app/layout.js
  client/src/app/page.jsx
  client/src/context/authContent.jsx
  server/package-lock.json
  server/package.json
  server/server/controllers/adminController.js
  server/server/controllers/userController.js
  server/server/index.js
  server/server/middleware/authMiddleware.js
  server/server/routes/adminRoutes.js
  server/server/routes/authenticationRoutes.js
  server/yarn.lock
Labels: bug, feature/enhancement

#132 Fix register function
  client/src/app/API/api.ts
  client/src/app/account/page.jsx
  client/src/app/auth/signup/page.jsx
  client/src/app/destination/[id]/page.jsx
  client/src/components/ReviewSection.jsx
  client/src/context/authContent.jsx
  server/server/controllers/reviewController.js
  server/server/models/reviewModel.js
  server/server/routes/reviewRoutes.js
  server/server/services/reviewService.js
Labels: bug

#139 Intergrated the favourites with the backend
  client/src/app/API/api.ts
  client/src/app/destination/[id]/page.jsx
  client/src/app/favourites/page.jsx
  client/src/app/layout.js
  client/src/context/authContent.jsx
  client/src/context/favourites.jsx
  server/server/controllers/favourites.js
  server/server/models/usersModel.js
Labels: documentation

#133 Language translations configuration
  client/src/components/ui/languageSelector.jsx
Labels: feature/enhancement

#135 Implement Language Selector Component
  client/src/components/ui/langaugeDropdown.jsx
Labels: feature/enhancement

#143 Initial i18next setup with custom backend for multi-language support
  client/src/i18next/i18next.js
  client/src/i18next/languageSelector.jsx
Labels: feature/enhancement

#141 Fixed functionality for forgot password
  AI/requirements.txt
  client/src/app/API/api.ts
  client/src/app/auth/forgot-password/page.jsx
  client/src/app/auth/reset-password/[...token]/page.jsx
  client/src/context/authContent.jsx
  server/server/controllers/userController.js
Labels: bug

#145 Made all the components functional
  client/src/app/API/api.ts
  client/src/app/destinationlist/category/[category]/page.jsx
  client/src/app/destinationlist/city/[city]/page.jsx
  client/src/app/destinationlist/province/[province]/page.jsx
  client/src/app/page.jsx
  client/src/components/Categorycards.jsx
  client/src/components/Cities.jsx
  client/src/components/Provinces.jsx
  client/src/components/Searchbar.jsx
Labels: bug

#148 Deployment prep
  Dockerfile
  client/next.config.mjs
  client/src/app/API/api.ts
  client/src/app/account/page.jsx
  client/src/app/destination/[id]/page.jsx
  client/src/app/page.jsx
  client/src/components/Chatbot.jsx
  client/src/components/Pagination.jsx
  client/src/components/ReviewSection.jsx
  client/src/context/authContent.jsx
  docker-compose.yml
  package-lock.json
  server/Dockerfile
  server/docker-compose.yml
  server/package.json
Labels: bug, feature/enhancement

#151 Add Multilingual Support for English, Turkish, and Arabic
  client/public/locales/ar/common.json
  client/public/locales/en/common.json
  client/public/locales/tr/common.json
Labels: feature/enhancement

#152 "Updated this file"
  client/src/i18next/i18n.js
Labels: feature/enhancement
